import { db } from "@/drizzle/client";
import { games } from "@/drizzle/schema/games";

import { createId } from "@paralleldrive/cuid2";

const STADIUM = {
  TORONTO: "ydlc7dutw7ugpoxhl5chosfx",
  VANCOUVER: "jg7bgb6yxc26hxleh4r4509p",
  MEXICO_CITY: "vdf14otu9txg2a88h7xxd024",
  GUADALAJARA: "tf47cr2tlg12kphiondve5wr",
  MONTERREY: "c7bg2mybub5klhdbawr7q28i",
  ATLANTA: "hsgndprw5vmhwu9u4ihbqako",
  BOSTON: "tytpyb9sfgbxx50xfniu1kc1",
  DALLAS: "i8dpr1fa59d3x5vwsz8gfgp5",
  HOUSTON: "gi318zrni496o1nxe36kgq21",
  KANSAS_CITY: "fhjzjwb990q349m0utmgefxv",
  LOS_ANGELES: "uiwp7rhmo7zisimqlm7bnl57",
  MIAMI: "ya8jb5bcsoqih23e92zsyur5",
  NEW_YORK: "l78yyxe85nzuuyqata2qglqj",
  PHILADELPHIA: "jqk47mgf845qavpvytbe04zk",
  SANTA_CLARA: "w69g71mffks8ppkkek4ex1ka",
  SEATTLE: "yshdw7z4ysqrd59nt6mger12",
};

export async function seedGroupStageGames() {
  await db.insert(games).values([
    // ======================
    // 1st ROUND
    // ======================

    // Group A
    {
      id: createId(),
      date: new Date("2026-06-11T19:00:00Z"),
      firstTeamId: "mex",
      secondTeamId: "rsa",
      phase: "group_stage",
      round: 1,
      group: "A",
      stadiumId: STADIUM.MEXICO_CITY,
    },
    {
      id: createId(),
      date: new Date("2026-06-12T01:00:00Z"),
      firstTeamId: "kor",
      secondTeamId: "cze",
      phase: "group_stage",
      round: 1,
      group: "A",
      stadiumId: STADIUM.GUADALAJARA,
    },

    // Group B
    {
      id: createId(),
      date: new Date("2026-06-12T19:00:00Z"),
      firstTeamId: "can",
      secondTeamId: "bih",
      phase: "group_stage",
      round: 1,
      group: "B",
      stadiumId: STADIUM.TORONTO,
    },
    {
      id: createId(),
      date: new Date("2026-06-13T16:00:00Z"),
      firstTeamId: "qat",
      secondTeamId: "sui",
      phase: "group_stage",
      round: 1,
      group: "B",
      stadiumId: STADIUM.SANTA_CLARA,
    },

    // Group C
    {
      id: createId(),
      date: new Date("2026-06-13T22:00:00Z"),
      firstTeamId: "bra",
      secondTeamId: "mar",
      phase: "group_stage",
      round: 1,
      group: "C",
      stadiumId: STADIUM.NEW_YORK,
    },
    {
      id: createId(),
      date: new Date("2026-06-14T01:00:00Z"),
      firstTeamId: "hti",
      secondTeamId: "sco",
      phase: "group_stage",
      round: 1,
      group: "C",
      stadiumId: STADIUM.BOSTON,
    },

    // Group D
    {
      id: createId(),
      date: new Date("2026-06-13T22:00:00Z"),
      firstTeamId: "usa",
      secondTeamId: "par",
      phase: "group_stage",
      round: 1,
      group: "D",
      stadiumId: STADIUM.LOS_ANGELES,
    },
    {
      id: createId(),
      date: new Date("2026-06-14T05:00:00Z"),
      firstTeamId: "aus",
      secondTeamId: "tur",
      phase: "group_stage",
      round: 1,
      group: "D",
      stadiumId: STADIUM.VANCOUVER,
    },

    // Group E
    {
      id: createId(),
      date: new Date("2026-06-14T17:00:00Z"),
      firstTeamId: "ger",
      secondTeamId: "cuw",
      phase: "group_stage",
      round: 1,
      group: "E",
      stadiumId: STADIUM.HOUSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-14T23:00:00Z"),
      firstTeamId: "civ",
      secondTeamId: "ecu",
      phase: "group_stage",
      round: 1,
      group: "E",
      stadiumId: STADIUM.PHILADELPHIA,
    },

    // Group F
    {
      id: createId(),
      date: new Date("2026-06-14T19:00:00Z"),
      firstTeamId: "ned",
      secondTeamId: "jpn",
      phase: "group_stage",
      round: 1,
      group: "F",
      stadiumId: STADIUM.DALLAS,
    },
    {
      id: createId(),
      date: new Date("2026-06-15T02:00:00Z"),
      firstTeamId: "swe",
      secondTeamId: "tun",
      phase: "group_stage",
      round: 1,
      group: "F",
      stadiumId: STADIUM.MONTERREY,
    },

    // Group G
    {
      id: createId(),
      date: new Date("2026-06-15T19:00:00Z"),
      firstTeamId: "bel",
      secondTeamId: "egy",
      phase: "group_stage",
      round: 1,
      group: "G",
      stadiumId: STADIUM.SEATTLE,
    },
    {
      id: createId(),
      date: new Date("2026-06-16T02:00:00Z"),
      firstTeamId: "irn",
      secondTeamId: "nzl",
      phase: "group_stage",
      round: 1,
      group: "G",
      stadiumId: STADIUM.LOS_ANGELES,
    },

    // Group H
    {
      id: createId(),
      date: new Date("2026-06-15T17:00:00Z"),
      firstTeamId: "esp",
      secondTeamId: "cpv",
      phase: "group_stage",
      round: 1,
      group: "H",
      stadiumId: STADIUM.ATLANTA,
    },
    {
      id: createId(),
      date: new Date("2026-06-15T23:00:00Z"),
      firstTeamId: "sau",
      secondTeamId: "uru",
      phase: "group_stage",
      round: 1,
      group: "H",
      stadiumId: STADIUM.MIAMI,
    },

    // Group I
    {
      id: createId(),
      date: new Date("2026-06-16T19:00:00Z"),
      firstTeamId: "fra",
      secondTeamId: "sen",
      phase: "group_stage",
      round: 1,
      group: "I",
      stadiumId: STADIUM.NEW_YORK,
    },
    {
      id: createId(),
      date: new Date("2026-06-16T23:00:00Z"),
      firstTeamId: "irq",
      secondTeamId: "nor",
      phase: "group_stage",
      round: 1,
      group: "I",
      stadiumId: STADIUM.BOSTON,
    },

    // Group J
    {
      id: createId(),
      date: new Date("2026-06-17T01:00:00Z"),
      firstTeamId: "aut",
      secondTeamId: "jor",
      phase: "group_stage",
      round: 1,
      group: "J",
      stadiumId: STADIUM.SANTA_CLARA,
    },
    {
      id: createId(),
      date: new Date("2026-06-17T02:00:00Z"),
      firstTeamId: "arg",
      secondTeamId: "alg",
      phase: "group_stage",
      round: 1,
      group: "J",
      stadiumId: STADIUM.KANSAS_CITY,
    },
    // Group K
    {
      id: createId(),
      date: new Date("2026-06-17T17:00:00Z"),
      firstTeamId: "por",
      secondTeamId: "cod",
      phase: "group_stage",
      round: 1,
      group: "K",
      stadiumId: STADIUM.HOUSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-18T02:00:00Z"),
      firstTeamId: "uzb",
      secondTeamId: "col",
      phase: "group_stage",
      round: 1,
      group: "K",
      stadiumId: STADIUM.MEXICO_CITY,
    },

    // Group L
    {
      id: createId(),
      date: new Date("2026-06-17T20:00:00Z"),
      firstTeamId: "eng",
      secondTeamId: "cro",
      phase: "group_stage",
      round: 1,
      group: "L",
      stadiumId: STADIUM.DALLAS,
    },
    {
      id: createId(),
      date: new Date("2026-06-17T23:00:00Z"),
      firstTeamId: "gha",
      secondTeamId: "pan",
      phase: "group_stage",
      round: 1,
      group: "L",
      stadiumId: STADIUM.TORONTO,
    },

    // round 2

    {
      id: createId(),
      date: new Date("2026-06-18T17:00:00Z"),
      firstTeamId: "cze",
      secondTeamId: "rsa",
      phase: "group_stage",
      round: 2,
      group: "A",
      stadiumId: STADIUM.ATLANTA,
    },
    {
      id: createId(),
      date: new Date("2026-06-19T01:00:00Z"),
      firstTeamId: "mex",
      secondTeamId: "kor",
      phase: "group_stage",
      round: 2,
      group: "A",
      stadiumId: STADIUM.GUADALAJARA,
    },

    // Group B
    {
      id: createId(),
      date: new Date("2026-06-18T16:00:00Z"),
      firstTeamId: "sui",
      secondTeamId: "bih",
      phase: "group_stage",
      round: 2,
      group: "B",
      stadiumId: STADIUM.LOS_ANGELES,
    },
    {
      id: createId(),
      date: new Date("2026-06-18T22:00:00Z"),
      firstTeamId: "can",
      secondTeamId: "qat",
      phase: "group_stage",
      round: 2,
      group: "B",
      stadiumId: STADIUM.VANCOUVER,
    },

    // Group C
    {
      id: createId(),
      date: new Date("2026-06-19T23:00:00Z"),
      firstTeamId: "sco",
      secondTeamId: "mar",
      phase: "group_stage",
      round: 2,
      group: "C",
      stadiumId: STADIUM.BOSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-20T00:30:00Z"),
      firstTeamId: "bra",
      secondTeamId: "hti",
      phase: "group_stage",
      round: 2,
      group: "C",
      stadiumId: STADIUM.PHILADELPHIA,
    },

    // Group D
    {
      id: createId(),
      date: new Date("2026-06-19T16:00:00Z"),
      firstTeamId: "usa",
      secondTeamId: "aus",
      phase: "group_stage",
      round: 2,
      group: "D",
      stadiumId: STADIUM.SEATTLE,
    },
    {
      id: createId(),
      date: new Date("2026-06-20T04:00:00Z"),
      firstTeamId: "tur",
      secondTeamId: "par",
      phase: "group_stage",
      round: 2,
      group: "D",
      stadiumId: STADIUM.SANTA_CLARA,
    },

    // Group E
    {
      id: createId(),
      date: new Date("2026-06-20T20:00:00Z"),
      firstTeamId: "ger",
      secondTeamId: "civ",
      phase: "group_stage",
      round: 2,
      group: "E",
      stadiumId: STADIUM.TORONTO,
    },
    {
      id: createId(),
      date: new Date("2026-06-21T01:00:00Z"),
      firstTeamId: "ecu",
      secondTeamId: "cuw",
      phase: "group_stage",
      round: 2,
      group: "E",
      stadiumId: STADIUM.KANSAS_CITY,
    },

    // Group F
    {
      id: createId(),
      date: new Date("2026-06-20T14:00:00Z"),
      firstTeamId: "ned",
      secondTeamId: "swe",
      phase: "group_stage",
      round: 2,
      group: "F",
      stadiumId: STADIUM.HOUSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-21T03:00:00Z"),
      firstTeamId: "tun",
      secondTeamId: "jpn",
      phase: "group_stage",
      round: 2,
      group: "F",
      stadiumId: STADIUM.MONTERREY,
    },

    // Group G
    {
      id: createId(),
      date: new Date("2026-06-21T16:00:00Z"),
      firstTeamId: "bel",
      secondTeamId: "irn",
      phase: "group_stage",
      round: 2,
      group: "G",
      stadiumId: STADIUM.LOS_ANGELES,
    },
    {
      id: createId(),
      date: new Date("2026-06-21T22:00:00Z"),
      firstTeamId: "nzl",
      secondTeamId: "egy",
      phase: "group_stage",
      round: 2,
      group: "G",
      stadiumId: STADIUM.VANCOUVER,
    },

    // Group H
    {
      id: createId(),
      date: new Date("2026-06-21T17:00:00Z"),
      firstTeamId: "esp",
      secondTeamId: "sau",
      phase: "group_stage",
      round: 2,
      group: "H",
      stadiumId: STADIUM.ATLANTA,
    },
    {
      id: createId(),
      date: new Date("2026-06-21T23:00:00Z"),
      firstTeamId: "uru",
      secondTeamId: "cpv",
      phase: "group_stage",
      round: 2,
      group: "H",
      stadiumId: STADIUM.MIAMI,
    },

    // Group I
    {
      id: createId(),
      date: new Date("2026-06-22T18:00:00Z"),
      firstTeamId: "fra",
      secondTeamId: "irq",
      phase: "group_stage",
      round: 2,
      group: "I",
      stadiumId: STADIUM.PHILADELPHIA,
    },
    {
      id: createId(),
      date: new Date("2026-06-22T21:00:00Z"),
      firstTeamId: "nor",
      secondTeamId: "sen",
      phase: "group_stage",
      round: 2,
      group: "I",
      stadiumId: STADIUM.NEW_YORK,
    },

    // Group J
    {
      id: createId(),
      date: new Date("2026-06-22T16:00:00Z"),
      firstTeamId: "arg",
      secondTeamId: "aut",
      phase: "group_stage",
      round: 2,
      group: "J",
      stadiumId: STADIUM.DALLAS,
    },
    {
      id: createId(),
      date: new Date("2026-06-23T00:00:00Z"),
      firstTeamId: "jor",
      secondTeamId: "alg",
      phase: "group_stage",
      round: 2,
      group: "J",
      stadiumId: STADIUM.SANTA_CLARA,
    },

    // Group K
    {
      id: createId(),
      date: new Date("2026-06-23T16:00:00Z"),
      firstTeamId: "por",
      secondTeamId: "uzb",
      phase: "group_stage",
      round: 2,
      group: "K",
      stadiumId: STADIUM.HOUSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-24T03:00:00Z"),
      firstTeamId: "col",
      secondTeamId: "cod",
      phase: "group_stage",
      round: 2,
      group: "K",
      stadiumId: STADIUM.GUADALAJARA,
    },

    // Group L
    {
      id: createId(),
      date: new Date("2026-06-23T17:00:00Z"),
      firstTeamId: "eng",
      secondTeamId: "gha",
      phase: "group_stage",
      round: 2,
      group: "L",
      stadiumId: STADIUM.BOSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-24T00:00:00Z"),
      firstTeamId: "pan",
      secondTeamId: "cro",
      phase: "group_stage",
      round: 2,
      group: "L",
      stadiumId: STADIUM.TORONTO,
    },

    // round 3

    // Group A
    {
      id: createId(),
      date: new Date("2026-06-25T01:00:00Z"),
      firstTeamId: "cze",
      secondTeamId: "mex",
      phase: "group_stage",
      round: 3,
      group: "A",
      stadiumId: STADIUM.MEXICO_CITY,
    },
    {
      id: createId(),
      date: new Date("2026-06-25T01:00:00Z"),
      firstTeamId: "rsa",
      secondTeamId: "kor",
      phase: "group_stage",
      round: 3,
      group: "A",
      stadiumId: STADIUM.MONTERREY,
    },

    // Group B
    {
      id: createId(),
      date: new Date("2026-06-24T16:00:00Z"),
      firstTeamId: "sui",
      secondTeamId: "can",
      phase: "group_stage",
      round: 3,
      group: "B",
      stadiumId: STADIUM.VANCOUVER,
    },
    {
      id: createId(),
      date: new Date("2026-06-24T16:00:00Z"),
      firstTeamId: "bih",
      secondTeamId: "qat",
      phase: "group_stage",
      round: 3,
      group: "B",
      stadiumId: STADIUM.SEATTLE,
    },

    // Group C
    {
      id: createId(),
      date: new Date("2026-06-24T23:00:00Z"),
      firstTeamId: "sco",
      secondTeamId: "bra",
      phase: "group_stage",
      round: 3,
      group: "C",
      stadiumId: STADIUM.MIAMI,
    },
    {
      id: createId(),
      date: new Date("2026-06-24T23:00:00Z"),
      firstTeamId: "mar",
      secondTeamId: "hti",
      phase: "group_stage",
      round: 3,
      group: "C",
      stadiumId: STADIUM.ATLANTA,
    },

    // Group D
    {
      id: createId(),
      date: new Date("2026-06-26T23:00:00Z"),
      firstTeamId: "tur",
      secondTeamId: "usa",
      phase: "group_stage",
      round: 3,
      group: "D",
      stadiumId: STADIUM.LOS_ANGELES,
    },
    {
      id: createId(),
      date: new Date("2026-06-26T23:00:00Z"),
      firstTeamId: "par",
      secondTeamId: "aus",
      phase: "group_stage",
      round: 3,
      group: "D",
      stadiumId: STADIUM.SANTA_CLARA,
    },

    // Group E
    {
      id: createId(),
      date: new Date("2026-06-25T20:00:00Z"),
      firstTeamId: "ecu",
      secondTeamId: "ger",
      phase: "group_stage",
      round: 3,
      group: "E",
      stadiumId: STADIUM.NEW_YORK,
    },
    {
      id: createId(),
      date: new Date("2026-06-25T20:00:00Z"),
      firstTeamId: "cuw",
      secondTeamId: "civ",
      phase: "group_stage",
      round: 3,
      group: "E",
      stadiumId: STADIUM.PHILADELPHIA,
    },

    // Group F
    {
      id: createId(),
      date: new Date("2026-06-26T00:00:00Z"),
      firstTeamId: "jpn",
      secondTeamId: "swe",
      phase: "group_stage",
      round: 3,
      group: "F",
      stadiumId: STADIUM.DALLAS,
    },
    {
      id: createId(),
      date: new Date("2026-06-26T00:00:00Z"),
      firstTeamId: "tun",
      secondTeamId: "ned",
      phase: "group_stage",
      round: 3,
      group: "F",
      stadiumId: STADIUM.KANSAS_CITY,
    },

    // Group G
    {
      id: createId(),
      date: new Date("2026-06-27T00:00:00Z"),
      firstTeamId: "egy",
      secondTeamId: "irn",
      phase: "group_stage",
      round: 3,
      group: "G",
      stadiumId: STADIUM.SEATTLE,
    },
    {
      id: createId(),
      date: new Date("2026-06-27T00:00:00Z"),
      firstTeamId: "nzl",
      secondTeamId: "bel",
      phase: "group_stage",
      round: 3,
      group: "G",
      stadiumId: STADIUM.VANCOUVER,
    },

    // Group H
    {
      id: createId(),
      date: new Date("2026-06-26T23:00:00Z"),
      firstTeamId: "cpv",
      secondTeamId: "sau",
      phase: "group_stage",
      round: 3,
      group: "H",
      stadiumId: STADIUM.HOUSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-27T01:00:00Z"),
      firstTeamId: "uru",
      secondTeamId: "esp",
      phase: "group_stage",
      round: 3,
      group: "H",
      stadiumId: STADIUM.GUADALAJARA,
    },

    // Group I
    {
      id: createId(),
      date: new Date("2026-06-26T18:00:00Z"),
      firstTeamId: "nor",
      secondTeamId: "fra",
      phase: "group_stage",
      round: 3,
      group: "I",
      stadiumId: STADIUM.BOSTON,
    },
    {
      id: createId(),
      date: new Date("2026-06-26T18:00:00Z"),
      firstTeamId: "sen",
      secondTeamId: "irq",
      phase: "group_stage",
      round: 3,
      group: "I",
      stadiumId: STADIUM.TORONTO,
    },

    // Group J
    {
      id: createId(),
      date: new Date("2026-06-28T01:00:00Z"),
      firstTeamId: "alg",
      secondTeamId: "aut",
      phase: "group_stage",
      round: 3,
      group: "J",
      stadiumId: STADIUM.KANSAS_CITY,
    },
    {
      id: createId(),
      date: new Date("2026-06-28T01:00:00Z"),
      firstTeamId: "jor",
      secondTeamId: "arg",
      phase: "group_stage",
      round: 3,
      group: "J",
      stadiumId: STADIUM.DALLAS,
    },

    // Group K
    {
      id: createId(),
      date: new Date("2026-06-28T00:30:00Z"),
      firstTeamId: "col",
      secondTeamId: "por",
      phase: "group_stage",
      round: 3,
      group: "K",
      stadiumId: STADIUM.MIAMI,
    },
    {
      id: createId(),
      date: new Date("2026-06-28T00:30:00Z"),
      firstTeamId: "cod",
      secondTeamId: "uzb",
      phase: "group_stage",
      round: 3,
      group: "K",
      stadiumId: STADIUM.ATLANTA,
    },

    // Group L
    {
      id: createId(),
      date: new Date("2026-06-27T22:00:00Z"),
      firstTeamId: "pan",
      secondTeamId: "eng",
      phase: "group_stage",
      round: 3,
      group: "L",
      stadiumId: STADIUM.NEW_YORK,
    },
    {
      id: createId(),
      date: new Date("2026-06-27T22:00:00Z"),
      firstTeamId: "cro",
      secondTeamId: "gha",
      phase: "group_stage",
      round: 3,
      group: "L",
      stadiumId: STADIUM.PHILADELPHIA,
    },
  ]);
}
``;
