import { db } from "./src/drizzle/client";
import { stadiums } from "./src/drizzle/schema/stadiums";
import { createId } from "@paralleldrive/cuid2";

export async function seedStadiums() {
  await db.insert(stadiums).values([
    // Canada
    {
      id: createId(),
      name: "Toronto Stadium",
      city: "Toronto",
      country: "Canada",
      countryCode: "CA",
      capacity: 45000,
      timezone: "America/Toronto",
    },
    {
      id: createId(),
      name: "BC Place Vancouver",
      city: "Vancouver",
      country: "Canada",
      countryCode: "CA",
      capacity: 54000,
      timezone: "America/Vancouver",
    },

    // Mexico
    {
      id: createId(),
      name: "Mexico City Stadium",
      city: "Mexico City",
      country: "Mexico",
      countryCode: "MX",
      capacity: 83000,
      timezone: "America/Mexico_City",
    },
    {
      id: createId(),
      name: "Guadalajara Stadium",
      city: "Guadalajara",
      country: "Mexico",
      countryCode: "MX",
      capacity: 48000,
      timezone: "America/Mexico_City",
    },
    {
      id: createId(),
      name: "Monterrey Stadium",
      city: "Monterrey",
      country: "Mexico",
      countryCode: "MX",
      capacity: 53500,
      timezone: "America/Monterrey",
    },

    // United States
    {
      id: createId(),
      name: "Atlanta Stadium",
      city: "Atlanta",
      country: "United States",
      countryCode: "US",
      capacity: 75000,
      timezone: "America/New_York",
    },
    {
      id: createId(),
      name: "Boston Stadium",
      city: "Boston",
      country: "United States",
      countryCode: "US",
      capacity: 65000,
      timezone: "America/New_York",
    },
    {
      id: createId(),
      name: "Dallas Stadium",
      city: "Dallas",
      country: "United States",
      countryCode: "US",
      capacity: 94000,
      timezone: "America/Chicago",
    },
    {
      id: createId(),
      name: "Houston Stadium",
      city: "Houston",
      country: "United States",
      countryCode: "US",
      capacity: 72000,
      timezone: "America/Chicago",
    },
    {
      id: createId(),
      name: "Kansas City Stadium",
      city: "Kansas City",
      country: "United States",
      countryCode: "US",
      capacity: 73000,
      timezone: "America/Chicago",
    },
    {
      id: createId(),
      name: "Los Angeles Stadium",
      city: "Los Angeles",
      country: "United States",
      countryCode: "US",
      capacity: 70000,
      timezone: "America/Los_Angeles",
    },
    {
      id: createId(),
      name: "Miami Stadium",
      city: "Miami",
      country: "United States",
      countryCode: "US",
      capacity: 65000,
      timezone: "America/New_York",
    },
    {
      id: createId(),
      name: "New York New Jersey Stadium",
      city: "East Rutherford",
      country: "United States",
      countryCode: "US",
      capacity: 82500,
      timezone: "America/New_York",
    },
    {
      id: createId(),
      name: "Philadelphia Stadium",
      city: "Philadelphia",
      country: "United States",
      countryCode: "US",
      capacity: 69000,
      timezone: "America/New_York",
    },
    {
      id: createId(),
      name: "San Francisco Bay Area Stadium",
      city: "Santa Clara",
      country: "United States",
      countryCode: "US",
      capacity: 71000,
      timezone: "America/Los_Angeles",
    },
    {
      id: createId(),
      name: "Seattle Stadium",
      city: "Seattle",
      country: "United States",
      countryCode: "US",
      capacity: 69000,
      timezone: "America/Los_Angeles",
    },
  ]);
}
