@baseUrl = http://localhost:3333
@token = SEU_TOKEN_AQUI

### Criar bolão
POST {{baseUrl}}/pools
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Bolão do Escritório"
}

### Entrar num bolão
POST {{baseUrl}}/pools/join
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "ABC123"
}

### Ver bolões do utilizador
GET {{baseUrl}}/pools
Authorization: Bearer {{token}}
